### PR TITLE
Py3 compatibility, some refactor

### PR DESCRIPTION
**Pull request by keflavich**
I've updated significant parts of the code base to be python3 compatible and switch to the python requests module for some tools.

I noticed the 'unmaintained' label in the description of the repository.  Are you just done with ADS<->bibdesk?

### CODE REVIEW

**Comment by jonathansick** [comment]
Hey @keflavich, very nice. That's right, I'm maintaining or using ADS to BibDesk anymore. Would you be interested in becoming the maintainer?

**Comment by keflavich** [comment]
Sure, you can add me as a maintainer.  I'm not very good at the automator side of things, but on the python side, I'm pretty sure I know what I'm doing.

**Comment by jonathansick** [comment]
Sweet! It's all yours. Thank you!

Sorry about the state of the code. It was all written before I knew what I was doing. Probably I'd burn it all down and re-do it, so its good to see a refactoring/modernization emphasis 😄 Anyways, do whatever you see fit.

Let me know your PyPI username and I can set you up to make releases too.

**Comment by keflavich** [comment]
My PyPI username is the same as my github name.

Are you using anything for paper tracking/downloading these days, or are you just done with that whole thing?

**Pull request merged**
